Add client and talk room fields to event
MetaProvide/adminly_calendar pull request #11
Opened 2022-08-03 12:40 UTC by oliveiraigorm

2022-08-05 09:02 UTC, frozenbanana submitted a review, later dismissed
We have used semi-colons everywhere on adminly so I am confused why the linting has not catched it. Lets stick to semi-colons.

2022-08-05 09:02 UTC, frozenbanana commented on src/components/Editor/Properties/PropertyTalkButton.vue
> +	<button v-if="!isSlot && !isReadOnly"
same

2022-08-05 09:02 UTC, frozenbanana commented on src/components/Editor/Properties/PropertyTalkButton.vue
> +			const NEW_LINE = '\r\n'
the NEW_LINE variable should be moved to one place. Perhaps Utils

2022-08-05 09:02 UTC, frozenbanana commented on src/components/Editor/Properties/PropertyClientPicker.vue
> +	border-color: var(--color-main-text) !important;
is `!important` really necessary?

2022-08-05 10:47 UTC, oliveiraigorm commented
> We have used semi-colons everywhere on adminly so I am confused why the linting has not catched it. Lets stick to semi-colons.

I guess lint here is not quite well configured since it was forked, maybe @mwalbeck has some input on that to make it more organized

2022-08-05 12:51 UTC, mwalbeck requested changes
If you add a video call link before adding a client, then when you add the client, the video call link gets removed.

Also can we get the select client to also show here:
![image](https://user-images.githubusercontent.com/19759293/183080934-be641584-d4be-4be1-866f-ac8ae6b1fcb8.png)

I think it'll create some confusion if you have selected a client, and it keeps saying "Select client"

2022-08-05 15:42 UTC, oliveiraigorm commented
> If you add a video call link before adding a client, then when you add the client, the video call link gets removed.
> 
> Also can we get the select client to also show here: ![image](https://user-images.githubusercontent.com/19759293/183080934-be641584-d4be-4be1-866f-ac8ae6b1fcb8.png)
> 
> I think it'll create some confusion if you have selected a client, and it keeps saying "Select client"

Did some changes improving it, with an add and one remove button. The styling of them is not complete and can be done on the other branch.

About the error I couldn't reproduce it, can you try again and tell me the specific steps?

2022-08-10 18:34 UTC, mwalbeck commented
The functionality is exactly what I was looking for. Now it's just the styling, and I think it should be an `x` instead of a `-` but do you want to deal with that in the other branch?

2022-08-11 13:26 UTC, oliveiraigorm commented
> The functionality is exactly what I was looking for. Now it's just the styling, and I think it should be an `x` instead of a `-` but do you want to deal with that in the other branch?

Yes, exactly. There's already a X SVG over there so that's what I had in mind

2022-08-11 13:57 UTC, mwalbeck approved these changes

2022-08-11 13:57 UTC, merged